RIAppDemo/RIAppDemo/Controllers/DemoController.cs
using System;
using System.Web.Mvc;
using System.Web.SessionState;
using System.Linq;

namespace RIAppDemo.Controllers
{
    //[SessionState(SessionStateBehavior.Required)]
    public class DemoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DataGridDemo()
        {
            return View();
        }

        public ActionResult ManyToManyDemo()
        {
            return View();
        }

        public ActionResult MasterDetailDemo()
        {
            return View(new RIAppDemo.Models.MasterDetailDemo());
        }

        public ActionResult CollectionsDemo()
        {
            return View();
        }

        public ActionResult BindingsDemo()
        {
            return View();
        }

        public ActionResult BrowserDemo()
        {
            return View();
        }

        public ActionResult SPADemo()
        {
            return View();
        }
    }
}

RIAppDemo/RIAppDemo/Views/Shared/_LayoutDemo.cshtml
@using RIAppDemo.Utils
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="cache-control" content="no-store" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="expires" content="timestamp" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Scripts/bootstrap/css/bootstrap.min.css",true)" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/redmond/jquery-ui-1.10.4.custom.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Scripts/jriapp/jriapp.css",true)" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css",true)" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Scripts/qtip/jquery.qtip.min.css",true)" rel="stylesheet" type="text/css" />

    
    @RenderSection("CssImport", false)
    <script src="@Url.Content("~/Scripts/jquery/jquery-2.1.0.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap/js/bootstrap.min.js",true)" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery/jquery-ui-1.10.4.custom.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/moment/moment.min.js",true)" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jriapp/jriapp_en.js",true)" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jriapp/jriapp.js",true)" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/qtip/jquery.qtip.min.js",true)" type="text/javascript"></script>
  
    @RenderSection("JSImport", false)    
</head>
<body>
<div class="container-fluid">
        <div class="row-fluid" style="border-bottom: 1px #5C87B2 solid;">
            <div class="span12" style="font-size:14px;">
               @Html.Partial("_MenuPartial")
            </div> 
        </div>
        <div>
            @RenderBody()
        </div>
        <footer>
            @RenderSection("Footer", false) 
        </footer>
    </div>

     @*invisible section to hold data template*@
    <section class="ria-template">
        @RenderSection("RiaTemplates", false)
        @*error dialog template*@
        <div id="errorTemplate" data-role="template">
            <div style="width: 100%; height: 100%; background-color: White; color: Red;">
                <div style="display: inline-block" data-bind="{this.value,to=message}">
                </div>
            </div>
        </div>
    </section>
</body>
</html>

RIAppDemo/RIAppDemo/Views/Shared/_MenuPartial.cshtml
 <nav>
    <ul class="nav nav-pills">  
       <li class="active">@Html.ActionLink("Home", "Index", "Demo")</li>  
       <li class="dropdown">  
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">DEMOs<b class="caret"></b></a>  
         <ul class="dropdown-menu">  
           <li>@Html.ActionLink("DataGrid demo", "DataGridDemo", "Demo")</li>  
           <li>@Html.ActionLink("Master-Details demo", "MasterDetailDemo", "Demo")</li>  
           <li>@Html.ActionLink("ManyToMany demo", "ManyToManyDemo", "Demo")</li>  
           <li>@Html.ActionLink("DataBinding demo", "BindingsDemo", "Demo")</li>  
           <li>@Html.ActionLink("Collections demo", "CollectionsDemo", "Demo")</li>  
           <li>@Html.ActionLink("Files and Folders browser demo", "BrowserDemo", "Demo")</li>
           <li>@Html.ActionLink("Single Page Application demo", "SPADemo", "Demo")</li>
        </ul>  
       </li>  
     </ul>  
 </nav>