RIAppDemo/RIAppDemo/Models/MasterDetailDemo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RIAppDemo.Models
{
    /// <summary>
    /// Example of containing databindings inside a model. So they are out of the page markup and more reusable.
    /// </summary>
    public class MasterDetailDemo
    {
        public MasterDetailDemo() 
        {
            this.BindGridCustomers = "{this.dataSource,to=dbSet,source=customerVM}{this.propChangedCommand,to=propChangeCommand,source=customerVM}";
            this.OptionsGridCustomers = "options={wrapCss:customerTableWrap,isHandleAddNew:true,editor:{templateID:customerEditTemplate,width:500,height:550,title:'Customer editing'},details:{templateID:customerDetailsTemplate}}";

            this.BindTableCustOrders = "{this.dataSource,to=dbSet,source=customerVM.ordersVM}{this.propChangedCommand,to=propChangeCommand,source=customerVM.ordersVM}";
            this.OptionsTableCustOrders = "options={isUseScrollIntoDetails:false,isHandleAddNew:true,editor:{templateID:orderEditTemplate,width:650,height:550,title:'Order editing'},details:{templateID:orderDetailsTemplate}}";

            this.BindAddNewOrder = "{this.command,to=addNewCommand,source=customerVM.ordersVM}";
            this.OptionsAddNewOrder = "options={tip:This is not a Real World example how to add an order!!!}";
        }

        public string BindGridCustomers {get; set;}
        public string OptionsGridCustomers { get; set; }

        public string BindTableCustOrders { get; set; }
        public string OptionsTableCustOrders { get; set; }

        public string BindAddNewOrder { get; set; }
        public string OptionsAddNewOrder { get; set; }
    }
}

RIAppDemo/RIAppDemo/Controllers/DemoController.cs
using System;
using System.Web.Mvc;
using System.Web.SessionState;
using System.Linq;

namespace RIAppDemo.Controllers
{
    //[SessionState(SessionStateBehavior.Required)]
    public class DemoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DataGridDemo()
        {
            return View();
        }

        public ActionResult ManyToManyDemo()
        {
            return View();
        }

        public ActionResult MasterDetailDemo()
        {
            return View(new RIAppDemo.Models.MasterDetailDemo());
        }

        public ActionResult CollectionsDemo()
        {
            return View();
        }

        public ActionResult BindingsDemo()
        {
            return View();
        }

        public ActionResult BrowserDemo()
        {
            return View();
        }

        public ActionResult SPADemo()
        {
            return View();
        }
    }
}

RIAppDemo/RIAppDemo/Controllers/RIAppDemoWebApiController.cs
using System.Net;
using System.Net.Http;
using System.Web.Http;
using RIAPP.DataService.Types;
using RIAppDemo.BLL.DataServices;
using RIAPP.DataService.WebApi;
using System.Threading.Tasks;

namespace RIAppDemo.Controllers
{
    public class RIAppDemoWebApiController : BaseWebApiController<RIAppDemoService>
    {
        public RIAppDemoWebApiController()
        {
        }
    }
}

RIAppDemo/RIAppDemo/Controllers/SSEWebApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web.Http;
using System.IO;
using System.Net.Http.Headers;
using System.Net;
using System.Collections.Concurrent;
using System.Threading;
using Newtonsoft.Json;
using System.Diagnostics;
using RIAppDemo.Models;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using System.Threading.Tasks;

namespace RIAppDemo.Controllers
{
    //Controller for Server side events
    public class SSEWebApiController : ApiController
    {
        private class Client: IDisposable
        {
            private StreamWriter _stream;
            private string _id;
            private DateTime _lastAccessTime;
            private DateTime _createdTime;
            private bool _isDisposed = false;

            public Client(StreamWriter stream, string id)
            {
                this._stream = stream;
                this._id = id;
                this._createdTime = DateTime.Now;
                this._lastAccessTime = this._createdTime;
            }

            public StreamWriter stream
            {
                get { return this._stream; }
            }

            public string id
            {
                get { return this._id; }
            }

            public DateTime lastAccessTime
            {
                get { return this._lastAccessTime; }
            }

            public DateTime CreatedTime
            {
                get { return this._createdTime; }
            }

            public void UpdateAccessTime()
            {
                this._lastAccessTime = DateTime.Now;
            }

            public async Task WriteAndSend(string data)
            {
                if (this._isDisposed)
                    return;
                this.UpdateAccessTime();
                await this.stream.WriteLineAsync("data:" + data + "\n");
                if (this._isDisposed)
                    return;
                await this.stream.FlushAsync();
            }

           
            protected virtual void Log(Exception ex)
            {
                SSEWebApiController.Log(ex);
            }

            public void Dispose()
            {
                try
                {
                    this._isDisposed = true;
                    this._stream.Close();
                }
                catch (Exception ex)
                {
                    Log(ex);
                }
            }

            public void Close()
            {
                this.Dispose();
            }
        }

        private const double CLIENT_TIME_OUT = 10;
        private static readonly Lazy<Timer> _cleanUpTimer = new Lazy<Timer>(() => new Timer(CleanUpTimerCallback, null, Timeout.Infinite, Timeout.Infinite));
        private static readonly ConcurrentDictionary<string, Client> _clients = new ConcurrentDictionary<string, Client>();
        private volatile static bool _isTimerEnabled = false;
        private volatile static int _clientCount = 0;
        private static Task _messagesTask;
        private static CancellationTokenSource _src;

        static SSEWebApiController()
        {
            _src = new CancellationTokenSource();
            var token = _src.Token;
            _messagesTask = new Task(() =>
            {
                var task = DoMessages(token);
                task.Wait();
            }, token, TaskCreationOptions.LongRunning);
            _messagesTask.Start();
        }

        private static async Task DoMessages(CancellationToken ct)
        {
            while (!ct.IsCancellationRequested)
            {
                try
                {
                    await TryGetAndPostMessages(ct);
                }
                catch (Exception ex)
                {
                    Log(ex);
                }
            }
            ct.ThrowIfCancellationRequested();
        }

        private static async Task TryGetAndPostMessages(CancellationToken ct)
        {
            //Demo Test: Generating Random messages at random intervals and send it to random clients
            Random rnd = new Random();
            await Task.Delay(rnd.Next(1000, 5000), ct);
            if (ct.IsCancellationRequested)
                return;
            Client client = null;
            //Get one Random client
            lock (_clients)
            {
                int cnt = _clients.Count();
                if (cnt > 0)
                {
                    int num = rnd.Next(100000) % cnt;
                    client = _clients.Skip(num).Take(1).Select(c=>c.Value).First();
                }
            }

            if (client == null)
                return;
            /*
            //Remove the clients after random intervals simulating different task times for each client
            if (DateTime.Now - client.CreatedTime > TimeSpan.FromSeconds(rnd.Next(60, 180)))
            {
                RemoveClient(client.id);
                return;
            }
           */

            string[] words = new string[] { "Test", "How", "Messaging", "Working", "Random", "Words", "For", "Demo", "Purposes", "Only", "Needed" };
            string message = "<b>Quote of the day</b>: <i>"+ string.Join(" ", words.Select(w => words[rnd.Next(0, 10)]).ToArray())+"</i>";
            SSEMessage msg = new SSEMessage() { clientID = client.id, payload = new Payload { message = message } };
            bool res = await PostMessage(msg);
        }

        protected static internal void Log(Exception ex)
        {
            System.Diagnostics.Debug.WriteLine(ex.Message);
        }

        [Authorize]
        public HttpResponseMessage Get(HttpRequestMessage request, string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }

            Guid parsedID = Guid.Parse(id);

            HttpResponseMessage response = request.CreateResponse();
            response.Headers.Add("Access-Control-Allow-Origin", "*");
            response.Headers.Add("Cache-Control", "no-cache, must-revalidate");
            var pushContent = new PushStreamContent((Stream stream, HttpContent content, TransportContext context) =>
            {
                StreamWriter streamwriter = new StreamWriter(stream);
                var client = new Client(streamwriter, id);
                lock (_clients)
                {
                    if (_clients.ContainsKey(client.id))
                        _RemoveClient(client.id);
                    bool isAdded = _clients.TryAdd(client.id, client);
                    if (isAdded)
                        ++_clientCount;
                }
                _CheckCleanUpTimer();
            }, "text/event-stream");
            response.Content = pushContent;
            return response;
        }

        [Authorize]
        [ActionName("PostMessage")]
        [HttpPost]
        public async Task<HttpResponseMessage> Post([FromBody] SSEMessage message)
        {
            bool res = await PostMessage(message);
            if (res)
            {
                var response = Request.CreateResponse(HttpStatusCode.Created);
                return response;
            }
            else
                return Request.CreateResponse(HttpStatusCode.NotFound);
        }

        [Authorize]
        [ActionName("CloseClient")]
        [HttpPost]
        public HttpResponseMessage Close(string id)
        {
            if (_RemoveClient(id))
                return Request.CreateResponse(HttpStatusCode.OK);
            else
                return Request.CreateResponse(HttpStatusCode.NotFound);
        }
       
        public static bool RemoveClient(string id)
        {
            return _RemoveClient(id);
        }

        //Cancel sending messages to clients
        public static void StopService()
        {
            _src.Cancel();
        }

        public static async Task<bool> PostMessage(SSEMessage message)
        {
            Client client;
            int cnt = _clients.Count();
            if (_clients.TryGetValue(message.clientID, out client))
            {
                try
                {
                    if (message.payload.message == "DUMMY")
                    {
                        client.UpdateAccessTime();
                    }
                    else
                    {
                        string data = JsonConvert.SerializeObject(message.payload);
                        await client.WriteAndSend(data);
                    }
                    return true;
                }
                catch (System.Web.HttpException)
                {
                    _RemoveClient(client.id);

                }
                catch (Exception)
                {
                    //also needs to log here
                    _RemoveClient(client.id);
                }

                return false;
            }
            else
                return false;
        }

        #region PRIVATE METHODS
        private static bool _RemoveClient(string id)
        {
            try
            {
                lock (_clients)
                {
                    Client client;
                    if (_clients.TryRemove(id, out client))
                    {
                        --_clientCount;
                        client.Dispose();
                        return true;
                    }
                }
                return false;
            }
            finally
            {
                _CheckCleanUpTimer();
            }
        }

        private static void _CheckCleanUpTimer()
        {
            lock (_cleanUpTimer)
            {
                if (!_isTimerEnabled && _clientCount > 0)
                {
                    Timer t = _cleanUpTimer.Value;
                    t.Change(TimeSpan.FromMinutes(CLIENT_TIME_OUT), TimeSpan.FromMinutes(CLIENT_TIME_OUT / 2));

RIAppDemo/RIAppDemo/Controllers/TemplatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.SessionState;
using RIAppDemo.BLL.DataServices;


namespace RIAppDemo.Controllers
{
    [SessionState(SessionStateBehavior.Disabled)]
    public class TemplatesController : Controller
    {
        public ActionResult Download(string name)
        {
            return View(name);
        }

        public ActionResult SPADemoTemplate1()
        {
            return View(new RIAppDemo.Models.SPATemplate());
        }

        public ActionResult SPADemoTemplate2()
        {
            return View(new RIAppDemo.Models.SPATemplate());
        }

        public ActionResult SPADemoTemplate3()
        {
            return View(new RIAppDemo.Models.SPATemplate());
        }

    }
}

RIAppDemo/RIAppDemo/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.SessionState;
using RIAppDemo.BLL.DataServices;
using RIAppDemo.Models;
using RIAPP.DataService.Mvc;
using RIAPP.DataService.Utils.Interfaces;

namespace RIAppDemo.Controllers
{
    [SessionState(SessionStateBehavior.Disabled)]
    public class UploadController : Controller
    {
        /// <summary>
        /// Used in FileApi action
        /// </summary>
        /// <returns></returns>
        private UploadedFile RetrieveFileFromRequest()
        {
            string filename = null;
            string fileType = null;
            int fileSize = 0;
            int id = -1;
            Stream fileContents = null;

            if (Request.Files.Count > 0)
            {
                //they're uploading the old way
                var file = Request.Files[0];
                fileSize = file.ContentLength;
                fileContents = file.InputStream;
                fileType = file.ContentType;
                filename = file.FileName;
            }
            else if (Request.ContentLength > 0)
            {
                fileSize = Request.ContentLength;
                fileContents = Request.InputStream;
                filename = Request.Headers["X-File-Name"];
                fileType = Request.Headers["X-File-Type"];
                id = int.Parse(Request.Headers["X-Data-ID"]);
            }

            return new UploadedFile()
            {
                FileName = filename,
                ContentType = fileType,
                FileSize = fileSize,
                Contents = fileContents,
                DataID = id
            };
        }

        public ActionResult Index()
        {
            return new EmptyResult();
        }
   
        public ActionResult ThumbnailUpload()
        {
            try
            {
                UploadedFile file = RetrieveFileFromRequest();

                if (file.FileName != null)
                {
                    string filename = Path.GetFileName(file.FileName);
                    if (filename != null)
                    {
                          var args = new RIAPP.DataService.ServiceArgs(new Serializer(), this.User);
                          RIAppDemoService svc = new RIAppDemoService(args);
                          using (svc)
                          {
                             svc.SaveThumbnail(file.DataID, file.FileName, file.Contents);
                          }
                    }
                }

                return new HttpStatusCodeResult(200);
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(400);
            }
        }
    }
}

RIAppDemo/RIAppDemo/Views/Demo/DataGridDemo.cshtml
@using System.Text
@using RIAPP.DataService
@using RIAppDemo.BLL.DataServices
@using RIAppDemo.Utils
@{
    Layout = "~/Views/Shared/_LayoutDemo.cshtml";
}
@{
    ViewBag.Title = "DataGrid Demo ";
}

@section CssImport
{
}

@section JSImport
{
    <script src="@Url.Content("~/Scripts/RIAppDemo/common.js",true)" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/RIAppDemo/header.js",true)" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/RIAppDemo/demoDB.js",true)" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/RIAppDemo/ssevents.js",true)" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/RIAppDemo/gridDemo.js",true)" type="text/javascript"></script>
}

<style type="text/css">
    #demoHeader label {
        color: Blue;
    }

    #demoContent {
        overflow: visible;
        height: 570px;
        vertical-align: top;
    }

    .productTableWrap {
        height: 100%;
        width: 100%;
    }

    .productTableContainer {
    }

    .productTableHeader {
    }

    .orderDetailTableWrap {
        max-height: 180px;
        width: 100%;
    }

    .number-display {
        color: Blue;
        font-weight: bold;
    }

    .number-edit input[type="text"] {
        color: Black;
    }

    .name-display {
        color: Blue;
        font-weight: bold;
    }

    .name-edit input[type="text"] {
        color: Black;
    }

    .name-edit textarea {
        color: Black;
    }

    .listbox-edit select {
        width: 75%;
    }

    .selectorCol {
        vertical-align: middle;
    }

    .selectorCell {
        text-align: center;
        vertical-align: middle;
    }

    .rowInactive {
        text-decoration: line-through;
        color: Gray;
    }

    table.ria-data-table tr:nth-child(even) {
        background-color: #ECF2F6;
    }

    .ui-datepicker select.ui-datepicker-month,
    .ui-datepicker select.ui-datepicker-year {
        min-height: 28px;
    }

    .ui-datepicker select.ui-datepicker-month {
        width: 80px;
        margin-right:3px;
    }
</style>

<script type="text/javascript">
    /*
      //this varable is declared in the GRIDDEMO module
       export var mainOptions: IMainOptions = {  service_url: null,
            permissionInfo: null,
            images_path: null,
            upload_thumb_url: null,
            templates_url: null,
            productEditTemplate_url: null,
            sizeDisplayTemplate_url: null,
            modelData: null,
            categoryData: null
        };
        //The Application is also declared and started in there
    */
    (function(ops){
        ops.images_path = '@Url.Content("~/Scripts/jriapp/img/")';
        //download template using ASP.NET MVC controller  - it first go through Razor engine to create links
        ops.templates_url = '@Url.Action("Download", "Templates", new {name="DataGridDemo"})';

        @*
        //these commented links were used to work with ASP.NET MVC controller (you can uncomment it ,and comment WEB API links)
        ops.service_url = '@Url.RouteUrl("Default",new {controller="RIAppDemoService", action=""})';
        ops.permissionInfo =  @Html.Action("PermissionsInfo", "RIAppDemoService");
        ops.upload_thumb_url = '@Url.Action("ThumbnailUpload", "Upload", null)';
        ops.productEditTemplate_url = '@Url.Action("DownloadTemplate", "Download", new {name="productEditTemplate"})';
        ops.sizeDisplayTemplate_url = '@Url.Action("DownloadTemplate", "Download", new { name = "sizeDisplayTemplate" })';
        ops.modelData = @Html.Action("ProductModelData", "RIAppDemoService");
        ops.categoryData = @Html.Action("ProductCategoryData", "RIAppDemoService");
        *@

        //these links are used to work with WEB API controller instead of ASP.NET MVC controller
        ops.service_url = '@Url.Action("", "RIAppDemoWebApi", new { httproute = "ApiByAction" })';
        ops.upload_thumb_url = '@Url.Action("UploadThumbnail", "File", new { httproute = "ApiByAction" })';
        ops.productEditTemplate_url = '@Url.Action("DownloadTemplate", "File", new { httproute = "ApiByName", name = "productEditTemplate" })';
        ops.sizeDisplayTemplate_url = '@Url.Action("DownloadTemplate", "File", new { httproute = "ApiByName", name = "sizeDisplayTemplate" })';

        //TESTING Server Side Events - uses Web API Controller
        @{
            var client_id = Guid.NewGuid().ToString();
        }
        ops.sse_clientID = '@client_id';
        ops.sse_url = '@Url.Action("Get", "SSEWebApi", new { httproute = "ApiById" })';
    })(RIAPP.GRIDDEMO.mainOptions);
</script>


<h2  style="display:inline-block;">@ViewBag.Title</h2>
<header id="title" style="width:99%; border:1px Solid LightBlue; padding:5px;margin-bottom:5px;-moz-border-radius: 4px;border-radius:4px;">
<a href="#" id="expander" style="margin-left:2px;" data-bind="{this.command,to=expanderCommand,mode=OneWay,source=headerVM}" data-view="name=expander"></a>
    <span style="margin-left:5px;">Filter</span>
    <span style="margin-left:5px;" data-bind="{this.html,to=sseMessage,mode=OneWay,source=app}"></span>
</header>
<form id="demoHeader" data-bind="{this.dataContext,source=productVM}" data-view="name=dataform">
    <table>
        <tr>
            <td>
              <label for="prodNum">Product Number:</label>
              <input type="text" id="prodNum" placeholder="Product number" data-bind-value="{this.value,to=filter.prodNumber,mode=TwoWay}" data-bind-toolTip="{this.toolTip,to=filter.searchTextToolTip}" />
            </td>
            <td>
               <label for="prodName">Name:</label>
               <input type="text" id="prodName" placeholder="Name" data-bind-1="{this.value,to=filter.name,mode=TwoWay}" data-bind-2="{this.toolTip,to=filter.searchTextToolTip}"  />
            </td>
            <td>
               <label for="prodMCat">Main Category:</label>
               <select id="prodMCat" size="1" class="span3" 
                    data-bind-1="{this.dataSource,to=filter.ParentCategories}" 
                    data-bind-2="{this.selectedValue,to=filter.parentCategoryID,mode=TwoWay}"
                    data-view="options:{valuePath=ProductCategoryID,textPath=Name}"></select>
            </td>
            <td>
                <label for="prodSCat">Sub Category:</label>
                <select id="prodSCat" size="1" class="span2" 
                    data-bind-1="{this.dataSource,to=filter.ChildCategories}" 
                    data-bind-2="{this.selectedValue,to=filter.childCategoryID,mode=TwoWay}"
                    data-bind-3="{this.selectedItem,to=filter.selectedCategory,mode=TwoWay}"
                    data-bind-4="{this.toolTip,to=filter.selectedCategory.Name}" 
                    data-view="options:{valuePath=ProductCategoryID,textPath=Name}"></select>
            </td>
            <td>
                <label for="prodMod">Model:</label>
                <select id="prodMod" size="1" class="span2" 
                    data-bind-1="{this.dataSource,to=filter.ProductModels}" 
                    data-bind-2="{this.selectedValue,to=filter.modelID,mode=TwoWay}"
                    data-bind-3="{this.toolTip,to=filter.selectedModel.Name}" 
                    data-bind-4="{this.selectedItem,to=filter.selectedModel,mode=TwoWay}"
                    data-view="options:{valuePath=ProductModelID,textPath=Name}"></select>
            </td>
        </tr>
         <tr>
            <td colspan="5">
              <div style="display:inline-block;">
              <label for="saleStart1">Sales Start Date Begin:</label>
              <input type="text" id="saleStart1" placeholder="Enter Date" data-bind="{this.value,to=filter.saleStart1,mode=TwoWay,converter=dateConverter}" data-view="name:datepicker,options={datepicker:{ showOn:button,yearRange:'-15:c',changeMonth: true,changeYear: true }}"/>
              </div>
              <div style="display:inline-block; margin-left:5px;">
              <label for="saleStart2">Sales Start Date End:</label>
              <input type="text" id="saleStart2" placeholder="Enter Date" data-bind="{this.value,to=filter.saleStart2,mode=TwoWay,converter=dateConverter}" data-view="name:datepicker,options={datepicker:{ showOn:button,yearRange:'-15:c',changeMonth: true,changeYear: true }}" />
              </div>
            </td>
        </tr>
    </table>
    <!--this nested dataform is only to test how the dataform nesting is working!!! it is not needed here, really.-->
    <div  data-bind="{this.dataContext}" data-view="name=dataform">
        <a id="btn_filter" class="btn btn-info btn-small" data-bind="{this.command,to=loadCommand}"><i class="icon-search"></i>&nbsp;Filter</a>
        <a id="btn_reset" class="btn btn-info btn-small" data-bind="{this.command,to=filter.resetCommand}"><i class="icon-retweet"></i>&nbsp;Reset</a>
    </div>
</form>

<div id="demoContent" data-bind="{this.isBusy,to=dbContext.isBusy}" data-view="name=busy_indicator">
    <div style="height:85%; vertical-align:top;">
    <table data-name="gridProducts" data-bind="{this.dataSource,to=dbSet,source=productVM}{this.propChangedCommand,to=propChangeCommand,source=productVM}" 
    data-view="options={wrapCss:productTableWrap,containerCss:productTableContainer,headerCss:productTableHeader,rowStateField:IsActive,isHandleAddNew:true,isCanEdit:true,editor:{templateID:productEditTemplate,width:550,height:650,submitOnOK:true,title:'Product editing'},details:{templateID:productDetailsTemplate}}">
        <thead>
        <tr>
            <th data-column="width:35px,type:row_expander"></th>
            <th data-column="width:50px,type:row_actions"></th>
            <th data-column="width:40px,type:row_selector,rowCellCss:selectorCell,colCellCss:selectorCol"></th>
            <th data-column="width:100px,sortable:true,title:ProductNumber" data-content="fieldName:ProductNumber,css:{displayCss:'number-display',editCss:'number-edit'},readOnly:true"></th>
            <th data-column="width:25%,sortable:true,title:Name" data-content="fieldName:Name,readOnly:true"></th>
            <th data-column="width:90px,title:'Weight',sortable:true" data-content="fieldName:Weight,readOnly:true"></th>
            <th data-column="width:15%,title=CategoryID,sortable:true,sortMemberName=ProductCategoryID" data-content= "fieldName=ProductCategoryID,name:lookup,options:{dataSource=dbContext.dbSets.ProductCategory,valuePath=ProductCategoryID,textPath=Name},readOnly:true"></th>
            <th data-column="width:100px,sortable:true,title='SellStartDate'" data-content="fieldName=SellStartDate,readOnly:true"></th>
            <th data-column="width:100px,sortable:true,title='SellEndDate'" data-content="fieldName=SellEndDate,readOnly:true"></th>
            <th data-column="width:90px,sortable:true,title='IsActive',sortMemberName=SellEndDate" data-content="fieldName=IsActive,readOnly:true"></th>
            <th data-column="width:10%,title=Size,sortable:true,sortMemberName=Size" data-content="template={displayID=sizeDisplayTemplate}"></th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
    </div>
     <div style="margin-top:40px;text-align:left; border:none;width:100%;height:15%">
        <!--pager-->
        <div style="float:left;" data-bind="{this.dataSource,to=dbSet,source=productVM}" data-view="name=pager,options={sliderSize:20,hideOnSinglePage=false}"></div>
        <div style="float:left; padding-left:10px;padding-top:10px;"><span>Total:</span>&nbsp;<span data-bind="{this.value,to=totalCount,source=productVM.dbSet}"></span>,&nbsp;&nbsp;<span>Selected:</span>&nbsp;<span data-bind="{this.value,to=selectedCount,source=productVM}"></span></div>

        <button class="btn btn-info btn-small" style="float:right;" data-bind="{this.command,to=addNewCommand,mode=OneWay,source=productVM}"><i class="icon-plus"></i>&nbsp;New Product</button>
     </div>
 </div>

@section RiaTemplates
{
    
}

RIAppDemo/RIAppDemo/Views/Demo/Index.cshtml
@{
    ViewBag.Title = "jRIAppTS - JavaScript RIA Framework DEMO";
}
@section CssImport 
{
    <style type="text/css">
        ul#DemoList > li
        {
            font-weight: bold;
            line-height: 1.8;
        }
        
        ul#DemoList ul
        {
            font-weight: normal;
        }
    </style>
}
<h2>@ViewBag.Title</h2>